openapi: 3.0.0
info:
  title: Incremental Review API
  version: 2.0.0
  description: |
    REST API endpoints for incremental literature review functionality.
    
    This API provides endpoints to:
    - Create continuation jobs from previous analyses
    - Extract gaps from completed reviews
    - Score paper relevance to identified gaps
    - Track job lineage (parent-child relationships)
    
    Part of the Literature Review Automation System's incremental mode feature.
  contact:
    name: Literature Review API Support
    url: https://github.com/BootstrapAI-mgmt/Literature-Review/issues

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /api/jobs/{job_id}/continue:
    post:
      summary: Create continuation job
      description: |
        Creates a new incremental analysis job that continues from a previous baseline job.
        The new job will:
        1. Extract gaps from the parent job
        2. Score new papers for relevance to those gaps
        3. Filter papers below the threshold
        4. Analyze only relevant papers
        5. Merge results back into the parent job's output
        
        This endpoint is used by the dashboard to implement incremental review mode.
      operationId: createContinuationJob
      tags:
        - Incremental Review
      parameters:
        - name: job_id
          in: path
          required: true
          description: The ID of the parent job to continue from
          schema:
            type: string
          example: "review_20250115_103000"
        - name: X-API-Key
          in: header
          required: true
          description: API key for authentication
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContinuationRequest'
      responses:
        '202':
          description: Continuation job queued successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContinuationJobResponse'
        '400':
          description: Bad request (invalid parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Parent job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized (missing or invalid API key)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /api/jobs/{job_id}/gaps:
    get:
      summary: Extract gaps from job
      description: |
        Extracts unfilled research gaps from a completed analysis job.
        Gaps are requirements with coverage below the specified threshold.
        
        Returns gaps grouped by pillar with:
        - Current coverage percentage
        - Target coverage percentage
        - Gap severity (high, medium, low)
        - Keywords associated with the gap
        - Sub-requirement IDs
      operationId: extractGaps
      tags:
        - Incremental Review
      parameters:
        - name: job_id
          in: path
          required: true
          description: The ID of the job to extract gaps from
          schema:
            type: string
          example: "review_20250115_103000"
        - name: threshold
          in: query
          required: false
          description: Minimum coverage threshold (gaps are below this value)
          schema:
            type: number
            format: float
            minimum: 0.0
            maximum: 1.0
            default: 0.7
          example: 0.7
        - name: X-API-Key
          in: header
          required: true
          description: API key for authentication
          schema:
            type: string
      responses:
        '200':
          description: Gaps extracted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GapsResponse'
        '404':
          description: Job not found or gap report missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized (missing or invalid API key)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/jobs/{job_id}/relevance:
    post:
      summary: Score paper relevance
      description: |
        Scores the relevance of papers to gaps identified in a job.
        Uses a combination of keyword matching and semantic similarity
        to predict which papers are likely to fill gaps.
        
        Returns relevance scores (0.0-1.0) for each paper.
      operationId: scorePaperRelevance
      tags:
        - Incremental Review
      parameters:
        - name: job_id
          in: path
          required: true
          description: The ID of the job with gaps to score against
          schema:
            type: string
          example: "review_20250115_103000"
        - name: X-API-Key
          in: header
          required: true
          description: API key for authentication
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelevanceRequest'
      responses:
        '200':
          description: Relevance scores computed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelevanceResponse'
        '400':
          description: Bad request (invalid papers data)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/jobs/{job_id}/lineage:
    get:
      summary: Get job lineage
      description: |
        Returns the lineage tree for a job, showing parent and child jobs.
        Useful for tracking incremental updates over time.
      operationId: getJobLineage
      tags:
        - Incremental Review
      parameters:
        - name: job_id
          in: path
          required: true
          description: The ID of the job to get lineage for
          schema:
            type: string
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lineage retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobLineageResponse'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ContinuationRequest:
      type: object
      required:
        - papers
      properties:
        papers:
          type: array
          description: New papers to analyze in continuation job
          items:
            $ref: '#/components/schemas/Paper'
        relevance_threshold:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          default: 0.50
          description: Minimum relevance score for papers to be analyzed
        prefilter_enabled:
          type: boolean
          default: true
          description: Whether to enable gap-targeted pre-filtering
        job_name:
          type: string
          description: Optional name for the continuation job
          example: "Review Update Jan 2025"
      example:
        papers:
          - DOI: "10.1000/paper1"
            Title: "New Neuromorphic Paper"
            Abstract: "This paper explores spike-timing dependent plasticity..."
            Authors: "Smith et al."
            Year: 2025
        relevance_threshold: 0.50
        prefilter_enabled: true
        job_name: "Review Update Jan 2025"
    
    RelevanceRequest:
      type: object
      required:
        - papers
      properties:
        papers:
          type: array
          items:
            $ref: '#/components/schemas/Paper'
        threshold:
          type: number
          format: float
          default: 0.50
          minimum: 0.0
          maximum: 1.0
      example:
        papers:
          - DOI: "10.1000/paper1"
            Title: "Neuromorphic Computing Advances"
            Abstract: "Recent advances in spike-timing..."
        threshold: 0.50
    
    Paper:
      type: object
      required:
        - Title
      properties:
        DOI:
          type: string
          description: Digital Object Identifier
          example: "10.1000/journal.paper"
        Title:
          type: string
          description: Paper title
          example: "Neuromorphic Computing with Spiking Neural Networks"
        Abstract:
          type: string
          description: Paper abstract
        Authors:
          type: string
          description: Comma-separated author names
          example: "Smith, J., Doe, A., Johnson, B."
        Year:
          type: integer
          description: Publication year
          example: 2025
    
    ContinuationJobResponse:
      type: object
      properties:
        job_id:
          type: string
          description: Unique ID of the new continuation job
          example: "review_20250120_143000"
        parent_job_id:
          type: string
          description: ID of the parent job being continued
          example: "review_20250115_103000"
        status:
          type: string
          enum: [queued, running, completed, failed]
          description: Current job status
        papers_to_analyze:
          type: integer
          description: Number of papers that will be analyzed (after filtering)
          example: 15
        papers_filtered:
          type: integer
          description: Number of papers filtered out below threshold
          example: 35
        total_papers:
          type: integer
          description: Total number of new papers submitted
          example: 50
        estimated_time_minutes:
          type: number
          format: float
          description: Estimated time to complete (minutes)
          example: 12.5
        estimated_cost_usd:
          type: number
          format: float
          description: Estimated API cost in USD
          example: 4.50
    
    GapsResponse:
      type: object
      properties:
        job_id:
          type: string
          example: "review_20250115_103000"
        total_gaps:
          type: integer
          description: Total number of gaps identified
          example: 23
        threshold:
          type: number
          format: float
          description: Coverage threshold used
          example: 0.7
        gaps:
          type: array
          items:
            $ref: '#/components/schemas/Gap'
        summary_by_pillar:
          type: object
          description: Gap counts grouped by pillar
          additionalProperties:
            type: integer
          example:
            "Pillar 1: Hardware": 5
            "Pillar 2: Algorithms": 8
            "Pillar 3: Applications": 10
    
    Gap:
      type: object
      properties:
        pillar_id:
          type: string
          example: "Pillar 1"
        pillar_name:
          type: string
          example: "Hardware Architectures"
        sub_requirement_id:
          type: string
          example: "1.2.1"
        description:
          type: string
          example: "Memristive devices for synaptic plasticity"
        current_coverage:
          type: number
          format: float
          description: Current coverage percentage (0.0-1.0)
          example: 0.45
        target_coverage:
          type: number
          format: float
          description: Target coverage threshold
          example: 0.70
        gap_severity:
          type: string
          enum: [high, medium, low]
          example: "high"
        keywords:
          type: array
          items:
            type: string
          example: ["memristor", "RRAM", "synaptic plasticity", "neuromorphic"]
    
    RelevanceResponse:
      type: object
      properties:
        scores:
          type: array
          items:
            type: object
            properties:
              paper_title:
                type: string
              relevance_score:
                type: number
                format: float
              relevant_gaps:
                type: array
                items:
                  type: string
                  description: Sub-requirement IDs this paper addresses
    
    JobLineageResponse:
      type: object
      properties:
        job_id:
          type: string
        parent_job_id:
          type: string
          nullable: true
        child_job_ids:
          type: array
          items:
            type: string
        lineage_depth:
          type: integer
          description: How many generations deep this job is
        created_at:
          type: string
          format: date-time
    
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        detail:
          type: string
          description: Detailed error information
        timestamp:
          type: string
          format: date-time

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

tags:
  - name: Incremental Review
    description: Endpoints for incremental literature review mode
